name: develop

on:
  push:
    branches:
      - 'develop'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: NotImplemneted yet
        run: echo "Not Implemented"
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        run: npm run test:ci
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: CoverageResult
          path: coverage
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: Dist
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: NotImplemneted yet
        run: echo "Not Implemented"
